//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoarding.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eMTkenya@stanbic.com")]
        public string EmailFrom {
            get {
                return ((string)(this["EmailFrom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wachiral@stanbic.com")]
        public string ErrorEmail {
            get {
                return ((string)(this["ErrorEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("4320")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
>>>>>>> 4a57cb65d9ff4345fc860a183a3da86a25aa01d6
        public int ClientOTPExpiry {
            get {
                return ((int)(this["ClientOTPExpiry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("2880")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
>>>>>>> 4a57cb65d9ff4345fc860a183a3da86a25aa01d6
        public int SignatoryOTPExpiry {
            get {
                return ((int)(this["SignatoryOTPExpiry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("2880")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
>>>>>>> 4a57cb65d9ff4345fc860a183a3da86a25aa01d6
        public int RepresentativeOTPExpiry {
            get {
                return ((int)(this["RepresentativeOTPExpiry"]));
            }
        }
<<<<<<< HEAD
=======

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PasswordExpiryDays
        {
            get
            {
                return ((int)(this["PasswordExpiryDays"]));
            }
        }
>>>>>>> 4a57cb65d9ff4345fc860a183a3da86a25aa01d6
    }
}
